### ISSUE TITLE
الحفظ القديم عم يجن

### ISSUE THREAD

**Issue by mhdothman** [muazweb/QTracker#9]
مرة ما بيقبل آخر 10 أجزاء
مرة ما بيقبل آخر 5 أجزاء
مرة ما بيقبل شي
مرة ما بيقبل آخر كم صفحة بالجزء الأول 
وفي مرة أدخلت لطالب قام ما قبل وعطاني صفحة مدري شو دين أبوها إنو في خطأ

**Comment by muazweb** [comment]
تم حل المسألة
